config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  mount Decidim::Core::Engine => '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Decidim::Admin::Engine.routes.draw do
  resources :navbars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/navbar.rb
class Navbar < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/decidim/admin/navbars_controller.rb
module Decidim
  module Admin
    # Controller that allows managing categories.
    class NavbarsController < Decidim::Admin::ApplicationController
      before_action :set_navbar, only: [:show, :edit, :update, :destroy]

      # GET /navbars
      def index
        @navbars = Navbar.all
      end

      # GET /navbars/1
      def show
      end

      # GET /navbars/new
      def new
        @navbar = Navbar.new
      end

      # GET /navbars/1/edit
      def edit
      end

      # POST /navbars
      def create
        @navbar = Navbar.new(navbar_params)

        if @navbar.save
          redirect_to @navbar, notice: 'Navbar was successfully created.'
        else
          render :new
        end
      end

      # PATCH/PUT /navbars/1
      def update
        if @navbar.update(navbar_params)
          redirect_to @navbar, notice: 'Navbar was successfully updated.'
        else
          render :edit
        end
      end

      # DELETE /navbars/1
      def destroy
        @navbar.destroy
        redirect_to navbars_url, notice: 'Navbar was successfully destroyed.'
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_navbar
          @navbar = Navbar.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def navbar_params
          params.require(:navbar).permit(:label, :url)
        end
    end
  end
end

app/controllers/decidim_controller.rb
# Entry point for Decidim. It will use the `DecidimController` as
# entry point, but you can change what controller it inherits from
# so you can customize some methods.
class DecidimController < ApplicationController
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  def create
    @menu = Menu.new(menu_params)

    if @menu.save
      redirect_to @menu, notice: 'Menu was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /menus/1
  def update
    if @menu.update(menu_params)
      redirect_to @menu, notice: 'Menu was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /menus/1
  def destroy
    @menu.destroy
    redirect_to menus_url, notice: 'Menu was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:label, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decidim/menu_helper.rb
# frozen_string_literal: true

# frozen_string_literal: true

module Decidim
    # This module includes helpers to manage menus in layout
    module MenuHelper
      # Public: Returns the main menu presenter object
      def main_menu
        Navbar.all
      end
  
      # Public: Returns the user menu presenter object
      def user_menu
        @user_menu ||= ::Decidim::InlineMenuPresenter.new(
          :user_menu,
          self,
          element_class: "tabs-title",
          active_class: "is-active",
          label: t("layouts.decidim.user_menu.title")
        )
      end
    end
  end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/navbars_helper.rb
module NavbarsHelper
end

app/views/decidim/admin/navbars/_form.html.erb
<%= form_with(model: navbar) do |form| %>
  <% if navbar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(navbar.errors.count, "error") %> prohibited this navbar from being saved:</h2>

      <ul>
        <% navbar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/decidim/admin/navbars/edit.html.erb
<h1>Editing Navbar</h1>

<%= render 'form', navbar: @navbar %>

<%= link_to 'Show', @navbar %> |
<%= link_to 'Back', navbars_path %>

app/views/decidim/admin/navbars/index.html.erb
<div class="card">
  <div class="card-divider">
    <h2 class="card-title">
      <a href="/admin/navbars/"> Gestionar Menu</a>
        <%= link_to 'New Navbar', new_navbar_path, class:"button tiny button--title" %>
    </h2>
  </div>
    <div class="card-section">
      <p id="notice"><%= notice %></p>
      <div class="table-scroll">
        <table class="table.list">
          <thead>
            <tr>
              <th>Label</th>
              <th>Url</th>
              <th colspan="3"></th>
            </tr>
          </thead>

                <tbody>
                  <% @navbars.each do |navbar| %>
                    <tr>
                      <td><%= navbar.label %></td>
                      <td><%= navbar.url %></td>
                      <td><%= link_to 'Show', navbar %></td>
                      <td><%= link_to 'Edit', edit_navbar_path(navbar) %></td>
                      <td><%= link_to 'Destroy', navbar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
          </table>
    </div>
  </div>
</div>

app/views/decidim/admin/navbars/new.html.erb
<h1>New Navbar</h1>

<%= render 'form', navbar: @navbar %>

<%= link_to 'Back', navbars_path %>

app/views/decidim/admin/navbars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @navbar.label %>
</p>

<p>
  <strong>Url:</strong>
  <%= @navbar.url %>
</p>

<%= link_to 'Edit', edit_navbar_path(@navbar) %> |
<%= link_to 'Back', navbars_path %>

app/views/layouts/decidim/_nuevo_nav.html.erb
<!-- nuevo nav!! -->

<nav class="main-nav">
    <ul>
        <% main_menu.each do |menu| %>
            <li class="main-nav__link">
            <a href="<%= menu.url %>">
                <%= menu.label%>
            </a>
            </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/decidim/_wrapper.html.erb
<%
if respond_to?(:current_component) && current_component && can_be_managed?(current_component)
  edit_link(
    manage_component_path(current_component),
    :read,
    :component,
    component: current_component,
    current_participatory_space: current_participatory_space
  )
end
%>

<!-- REDESIGN_PENDING: Remove when redesigned is finished -->
<div class="off-canvas-wrapper">
  <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
    <div class="off-canvas position-right hide-for-large" data-position="right"
         id="offCanvas" data-off-canvas>
      <!-- Close button -->
      <button class="close-button"
              aria-label="<%= t("layouts.decidim.header.close_menu") %>" type="button"
              data-close>
        <span aria-hidden="true">&times;</span>
      </button>
      <!-- Menu -->
      <div class="hide-for-medium" data-set="nav-holder"></div>
      <div class="hide-for-medium usermenu-off-canvas-holder"
           data-set="nav-login-holder"></div>
      <div class="hide-for-medium mt-s ml-s mr-s search-off-canvas-holder"
           data-set="nav-search-holder"></div>
    </div>
    <div class="off-canvas-content" data-off-canvas-content>
      <div class="footer-separator">
        <!--separates the footer from the rest of the page,
             creates a sticky footer-->
        <div class="header" role="banner">
          <!-- Topbar -->
          <div class="title-bar">
            <%= link_to t("skip_button", scope: "decidim.accessibility"), url_for(anchor: "content"), class: "skip" %>
            <% if current_organization.official_img_header.attached? %>
              <%= link_to  current_organization.official_url, class: "logo-cityhall" do %>
                <%= image_tag current_organization.attached_uploader(:official_img_header).path, alt: current_organization.name %>
              <% end %>
            <% end %>
            <div class="row column topbar">
              <div class="logo-wrapper">
                <%= render partial: "layouts/decidim/logo", locals: { organization: current_organization } %>
              </div>
              <%= render partial: "layouts/decidim/topbar_search" %>
              <%= render partial: "layouts/decidim/language_chooser" %>
              <div class="hide-for-medium topbar__menu">
                <button type="button" data-toggle="offCanvas" aria-label="<%= t("layouts.decidim.header.navigation") %>">
                  <%= icon "menu", aria_label: t("layouts.decidim.header.navigation"), role: "img" %>
                </button>
              </div>
              <% if current_user %>
                <nav class="topbar__dropmenu topbar__user__logged" aria-label="<%= t("layouts.decidim.header.user_menu") %>">
                  <%= link_to decidim.notifications_path, class: "topbar__notifications #{current_user.notifications.any? ? "is-active" : ""}" do %>
                    <%= icon "bell", role: "img", aria_label: t("layouts.decidim.user_menu.notifications") %>
                  <% end %>
                  <%= link_to decidim.conversations_path, class: "topbar__conversations #{current_user.unread_conversations.any? ? "is-active" : ""}" do %>
                    <%= icon "envelope-closed", role: "img", aria_label: t("layouts.decidim.user_menu.conversations") %>
                  <% end %>
                  <ul class="dropdown menu" data-dropdown-menu
                    data-autoclose="false"
                    data-disable-hover="true"
                    data-click-open="true"
                    data-close-on-click="true"
                    role="menubar">
                    <li class="is-dropdown-submenu-parent show-for-medium" role="presentation">
                      <%= link_to current_user.name, decidim.account_path, id: "user-menu-control", "aria-controls": "user-menu", "aria-haspopup": "menu", "aria-label": t("layouts.decidim.user_menu.account", name: current_user.name), "role": "menuitem" %>
                      <ul class="menu is-dropdown-submenu" id="user-menu" role="menu" aria-labelledby="user-menu-control">
                        <%= render partial: "layouts/decidim/user_menu" %>
                      </ul>
                      <div data-set="nav-login-holder" class="show-for-medium">
                        <!-- Repeated due to dropdown limitations -->
                        <ul class="menu is-dropdown-submenu js-append usermenu-off-canvas">
                          <%= render partial: "layouts/decidim/user_menu" %>
                        </ul>
                      </div>
                    </li>
                  </ul>
                </nav>
              <% else %>
                <div class="topbar__user show-for-medium" data-set="nav-login-holder">
                  <div class="topbar__user__login js-append">
                    <% if current_organization.sign_up_enabled? %>
                      <%= link_to t("layouts.decidim.header.sign_up"), decidim.new_user_registration_path, class: "sign-up-link" %>
                    <% end %>
                    <%= link_to t("layouts.decidim.header.sign_in"), decidim.new_user_session_path, class: "sign-in-link" %>
                  </div>
                </div>
              <% end %>
              <%= render partial: "layouts/decidim/admin_links" %>
            </div>
          </div>
          <div class="show-for-medium" data-set="nav-holder">
            <div class="navbar js-append">
              <div class="row column">
              <%= render partial: "layouts/decidim/nuevo_nav" %>
              </div>
            </div>
          </div>
        </div>

        <main id="content" data-content>
          <%= display_flash_messages %>
          <%= yield %>
        </main>
      </div>
      <div class="footer" role="contentinfo">
        <%= render partial: "layouts/decidim/main_footer" %>
        <%= render partial: "layouts/decidim/mini_footer" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/decidim/admin/_application.html.erb
<% add_decidim_page_title(t("titles.panel", scope: "decidim.admin")) %>
<% add_decidim_page_title(current_organization.name) %>
<!doctype html>
<html class="no-js" lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="author" content="">
    <meta name="copyright" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= decidim_page_title %></title>
    <%= render partial: "layouts/decidim/admin/header" %>
  </head>
  <body>
    <%= render partial: "layouts/decidim/timeout_modal" %>
    <%= render partial: "layouts/decidim/admin/template_top" %>
    <div class="layout-nav">
      <%= main_menu.render %>
            <nav class="main-nav" aria-label="Menú principal">
      <ul>
      <li>
      <a href="/admin/navbars/">
      <svg aria-label="dashboard" role="img" aria-hidden="true" class="icon--dashboard icon"><title>dashboard</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-dashboard"></use></svg>
      Gestionar Menu</a>
      </li>
      </ul>
      </nav>
      <%= yield :secondary_nav if content_for? :secondary_nav %>
      <%= yield :sidebar_menu_nav if content_for? :sidebar_menu_nav %>
    </div>
    <div class="layout-content">
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <%= render partial: "layouts/decidim/admin/template_bottom" %>
    <%= render partial: "decidim/shared/confirm_modal" %>
    <%= render partial: "layouts/decidim/admin/js_configuration" %>
    <%= render partial: "layouts/decidim/cors" if Decidim.cors_enabled %>

    <%= snippets.display(:foot) %>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.label %></td>
        <td><%= menu.url %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @menu.label %>
</p>

<p>
  <strong>Url:</strong>
  <%= @menu.url %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>